### ISSUE TITLE
read-dictionary and read-list read additional byte from stream

### ISSUE THREAD

**Issue by felixr** [cmiles74/bencode#10]
In `read-dictionary` and `read-list` the code uses `match-byte` to check that the value is properly terminated:
https://github.com/cmiles74/bencode/blob/0d57959aeea5135cc97503ac30e0656aaf7633b3/src/bencode.janet#L188

But `match-byte` also advances to the next byte in the stream. If this is a network stream we possibly wait forever to get a next byte and never return the fully parsed value.

A quick fix is to just use `peek-byte` when we are parsing a top-level list or dictionary. I implemented this in 
https://github.com/felixr/bencode/commit/c4c59e0fcea6af08a00509b8702ee4affd5fb81a

It looks like it is working, but I admittedly have not tried hard to make it nice and went with the first thing that came to my mind.

**Comment by cmiles74** [comment]
I can see what you mean! I added[ four new tests based on the code in your branch](https://github.com/cmiles74/bencode/compare/network-read?expand=1), the two you had plus two more for nested lists and dictionaries.

Would you like to submit a pull request?

**Comment by felixr** [comment]
I created PR https://github.com/cmiles74/bencode/pull/11 I did not incorporate your additional tests; I assume you will just merge them afterwards.

PS: Thanks for your quick reply!

**Comment by cmiles74** [comment]
This looks good, it's been merged in. Thank you! 😀👍
